server:
  port: 8080

spring:
  application:
    name: account-service
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: SYSTEM
    password: AdminP@ssWord
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.OracleDialect

jasypt:
  encryptor:
    bean: encryptorBean
        
auth:
  users:
    - username: admin
      password: ENC(M5zNz8B706z2Uwdw90ktjE7Pa3FjXrvE)
      roles: [ADMIN]
    - username: user1
      password: ENC(M5zNz8B706z2Uwdw90ktjE7Pa3FjXrvE)
      roles: [USER]
    
